### PR TITLE
ENYO-1308: Placeholder background color

### PR DESCRIPTION
**Pull request by KunmyonChoi**
- Add a backgroundColor property into enyo.Image.
- Add a condition to skip unnecessary DOM access on create

DCO-1.1-Signed-Off-By: Kunmyon Choi kunmyon.choi@lge.com

### CODE REVIEW

**Comment by aarontam** [comment]
Hi @KunmyonChoi, we are implementing something along the same lines for ENYO-510 (see https://github.com/enyojs/enyo/pull/1095, https://github.com/enyojs/enyo/pull/1056, https://github.com/enyojs/layout/pull/123, and https://github.com/enyojs/moonstone/pull/2010). I wonder if we shouldn't try to consolidate this work with the other feature and/or at least take into account the techniques being used there?

**Comment by KunmyonChoi** [comment]
Hi @aarontam , actually I tried also the onload technique for placeholder color. Because, I found that onload event only comes when I am using img tag but not comes from background-image. What I found is set src first then switch src to background-image on onload handler. I think @ryanjduffy 's technique is also do the same. I asked to GUI designer about the exact requirement to make the requirement simple. And she said that it doesn't need to be reset the background color after load. Which means image can be displayed with background color even when image has transparent background.

**Comment by aarontam** [comment]
Ah ha, makes sense! I think another part of my question was considering the case when `placeholder` and `backgroundColor` are both set, and which gets precedence, and other potential interference cases.

**Comment by lishammel** [comment]
@KunmyonChoi  - do we need this PR anymore? The Jira is closed as "will not fix". Thanks.

**Pull request closed without merging**
