### PR TITLE
ENYO-1743: Adding resolution independence to 2.5.3

### PR DESCRIPTION
**Pull request by Djspaceg**

### CODE REVIEW

**Comment by ybsung** [comment]
@Djspaceg 
Could I know the history why the modification in source/ui/data/VerticalDelegate.js is needed for release-2.5.3-pre.20.wb because we want to reduce any change for release-2.5.3-pre.20.wb?

**Comment by Djspaceg** [comment]
It's not directly needed, it just came over with the merge. It fixes a bug that caused list items to not show up properly. We were planning on taking it out, unless you'd like to keep it.

**Comment by ybsung** [comment]
In my opinion, it's better to take out it for this version and apply it into next version if we need.

Thanks so much.

**Comment by aarontam** [comment]
Hi @ybsung, we've created a version without any of the unwanted changes/fixes here: https://github.com/enyojs/enyo/pull/1190. We'll test this thoroughly before getting it merged, thanks!

**Comment by ybsung** [comment]
Thanks a lot.

**Comment by aarontam** [comment]
Closing in favor of https://github.com/enyojs/enyo/pull/1190.

**Pull request closed without merging**
