### PR TITLE
Implemented a parser to handle nested url() properties in css

### PR DESCRIPTION
**Pull request by Rayraz**
This pull request is intended as a fix for: https://enyojs.atlassian.net/browse/ENYO-4129

I've implemented a small parser that finds url() properties in css and does not break on nested url() properties in data uri's. Works both with quoted and unquoted url strings as well as unbalanced parenthesis.

### CODE REVIEW

**Comment by Rayraz** [comment]
Here's a stand-alone implementation of the parser:

```javascript
(function() {

	"use strict";

	var code = [
		"background-image: (); ",
		"background-image: url(); ",
		"background-image: url(''); ",
		"background-image: url(\"\"); ",
		"background-image: url('image.png'); ",
		"background-image: url(\"image.png\"); ",
		"background-image: url('some string with \"nested\" 'quotes', cuz we test it like that'); ",
		"background-image: url('data:svg+xml;%3Csvg%3E%3Cgradient%20id%3D%5C%22gradient%5C%22%3E%3C%2Fgradient%3E%3Crect%20fill%3D%5C%22url(%23gradient)%5C%22%3E%3C%2Frect%3E%3C%2Fsvg%3E');",
		"url(kitchensink test) with url(some string with \"nested\" 'quotes' and URL(\"nested url() props\"), unbalanced 'quotes and parenthesis \\) just); to url('\'be \'sure\' )');",
		"Blake likes this background-image: url('%3Csvg%20height%3D%2230%22%20width%3D%22200%22%3E%0A%20%20%20%20%3ClinearGradient%20id%3D%22gradient%22%20gradientUnits%3D%22userSpaceOnUse%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%220%25%22%3E%0A%20%20%20%20%20%20%20%20%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%23ff0000%22%2F%3E%0A%20%20%20%20%20%20%20%20%3Cstop%20offset%3D%2230%25%22%20stop-color%3D%22%23008000%22%2F%3E%0A%20%20%20%20%20%20%20%20%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%230000ff%22%2F%3E%0A%20%20%20%20%3C%2FlinearGradient%3E%0A%20%20%20%20%3Ctext%20x%3D%220%22%20y%3D%2215%22%20fill%3D%22url(%23gradient)%22%3E5%3A-)%20Elvis%20Smiley%3C%2Ftext%3E%0A%3C%2Fsvg%3E');"
	].join("");

	// Parses urlPaths out of codeIn, rewrites relative paths, and returns the
	// result.
	//
	// Parsing process:
	// - Split code on 'url(' fragments.
	// - Once a 'url(' fragment is encountered, a url() property string will be
	//   parsed character by character.
	// - Once inside a 'url()' property, check if it's value is a quoted string.
	// - If url() value is a quoted string:
	//   - Look for unescaped closing quote and parenthesis. (escape char is "\")
	// - If url() value is an unquoted string:
	//   - Look for nested balanced pairs of unescaped parenthesis. (escape char is "\")
	//   - Look for on-nested unescaped closing parenthesis.
	// - Fix url path, append fixed path to output.
	// - Append the rest of the split fragment to output.
	var fixUrlPaths = function(codeIn) {
		var codeOut = "";
		var partials = codeIn.split(/url\(/ig);
		var partial;
		var urlProp = "";
		var nested;
		var quote;
		var i;

		// Start new url() property
		var startUrlProp = function() {
			urlProp = "url(";
			nested = 0;
			quote = partial[0] === "'" || partial[0] === "\"" ? partial[0] : null;
		};

		// Fixes relative paths in url() property, ignores external urls and
		// data uri's.
		var fixUrlPath = function() {
			var urlPath;
			var urlPathTrimmed;
			var relPath;

			// Find url path, ignore quotes in url string
			urlPath = urlProp.slice(4, -1);
			urlPathTrimmed = urlPath.split(/^['"]|['"]$/)[1];
			urlPath = urlPathTrimmed === undefined ? urlPath : urlPathTrimmed;

			// handle the case url('') or url("").
			if (!urlPath) {
				return "url()";
			}
			// skip an external url (one that starts with <protocol>: or just //, includes data:)
			if (/^([\w-]*:)|(\/\/)/.test(urlPath)) {
				return "url('" + urlPath + "')";
			}

			// Make relative asset path from 'top-of-the-tree/build'
			// var relPath = path.join("..", opt.relsrcdir, path.dirname(sheet), urlPath);
			// if (process.platform == "win32") {
			//     relPath = pathSplit(relPath).join("/");
			// }
			relPath = "rewritten";

			// console.log("opt.relsrcdir:", opt.relsrcdir);
			// console.log("sheet:", sheet);
			return "url('" + relPath + "')";
		};

		// Finalize url() property
		var finalizeUrlProp = function() {
			// Fix url path
			urlProp = fixUrlPath(urlProp);
			// Add fixed urlPath and the rest of this partial
			// to final output
			codeOut += urlProp + partial.substr(i + 1);
			// Clear urlProp and continue to next partial.
			urlProp = "";
		};

		// Start parsing
		if(codeIn.substr(0,4) === "url(") {
			partial = partials[0];
			startUrlProp();
		}
		codeOut = partials.shift();

		// From this point onwards, each partial contains at least part of a
		// url() property.
		iteratePartials: while (partials.length) {
			partial = partials.shift();

			// If we are not already parsing a url() property, create a new one.
			if (!urlProp.length) {
				startUrlProp();
			} else if(urlProp.length > 4) {
				urlProp += "url(";
				++nested;
			}

			// Complete url property
			for (i = 0; i < partial.length; i++) {
				urlProp += partial[i];

				// Quoted url property string ends with and un-escaped quote,
				// followed by a closing parenthesis.
				if (quote &&
					partial[i] === quote &&
					partial[i - 1] !== "\\" &&
					partial[i + 1] === ")") {
					// Append closing parenthesis;
					urlProp += partial[i + 1];
					++i;
					finalizeUrlProp();
					continue iteratePartials;
				}

				// Unquoted url property string ends with an un-escaped closing
				// parenthesis
				else if (!quote &&
					nested === 0 &&
					partial[i] === ")" &&
					partial[i - 1] !== "\\") {
					finalizeUrlProp();
					continue iteratePartials;
				}

				// Intercept un-escaped nested parenthesis in unquoted url()
				// value strings. (Unbalanced parenthesis are escaped and can be
				// ignored)
				else if(!quote &&
				partial[i] === "(" &&
				partial[i - 1] !== "\\") {
					++nested;
				}
				else if(!quote &&
					partial[i] === ")" &&
					partial[i - 1] !== "\\") {
					--nested;
				}
			}
		}

		return codeOut;
	};

	// Speed test
	var startTime = Date.now();
	var longCode = new Array(1001).join(code);
	code = fixUrlPaths(longCode);
	var timeSpent = Date.now() - startTime;
	console.log(timeSpent);

	// Output
	return fixUrlPaths(code);
})();
```

**Comment by lishammel** [comment]
Thanks for submitting - we've got this in the queue to review.

**Comment by Rayraz** [comment]
Enyo-DCO-1.1-Signed-off-by: Ruben Vreeken ruben.vreeken@gmail.com

**Comment by lishammel** [comment]
Closing out - not applicable to Enyo 2.6 and we won't make additional releases against Enyo 2.5.

**Pull request closed without merging**
