### PR TITLE
Fixes PLAT-13424 prevent setting dragging when not really dragging

### PR DESCRIPTION
**Pull request by ryanjduffy**
Enyo-DCO-1.1-Signed-off-by: Ryan Duffy (ryan.duffy@lge.com)

### CODE REVIEW

**Comment by ybsung** [comment]
@ryanjduffy 
There is still 'transitioning" class when testing this PR with ConfirmPanelSample.

Workspace:
Enyo : PLAT-13424-ryanjduffy branch
enyo-strawman : release-2.6.1-pre.2 branch
garnet : 1.5.0-pre.3.1 tag or 1.5.0-dev branch

**Comment by ybsung** [comment]
The css below was applied.
```
.g-panelmanager .enyo-view.transitioning {
  border-radius: 50%
}
```

**Comment by ryanjduffy** [comment]
@ybsung Good catch. Missed some necessary logic which I've added in another commit. Thanks!

**Comment by ybsung** [comment]
@ryanjduffy 
I reported one issue in https://jira2.lgsvl.com/browse/PLAT-13424. Could you check it?

**Comment by ybsung** [comment]
@ryanjduffy 
The code in this PR was merged into release-2.6.1-pre.3 because the issues reported before were fixed and only one new issue that I reported was not fixed.

**Comment by ybsung** [comment]
It looks good to me.

**Pull request merged**
