### PR TITLE
Fixes ENYO-1140

### PR DESCRIPTION
**Pull request by ryanjduffy**
## Issue
The less.js injection script assumes it will be located in <app-root>/enyo/tools and therefore hard codes the path to the actual LESS script relative to <app-root>. If enyo is in a shared location (or were moved into lib), the path would be incorrect.

## Fix
Determine path to LESS based on src of LESS loader script tag

Enyo-DCO-1.1-Signed-off-by: Ryan Duffy (ryan.duffy@lge.com)

### CODE REVIEW

**Comment by aarontam** [comment]
@ryanjduffy this is great - we should be able to update the Moonstone samples to take advantage of this change, once it's been integrated.

**Comment by ryanjduffy** [comment]
Good call. Forgot about the ugly paths they all have. Did you open a ticket for that already?

**Comment by aarontam** [comment]
Nope not yet - I had created a branch with an updated set of samples, but ran into this issue you've resolved, in the course of the resolution-independence work. I'll create a PR. :+1:

**Comment by aarontam** [comment]
@ryanjduffy just remembered we had created a separate `less-ri.js` file so that developers could opt-out from using the resolution-independent version of LESS (i.e. https://github.com/enyojs/bootplate-moonstone/blob/master/debug.html#L16). Can we also make the same updates to this script as well?

**Comment by lishammel** [comment]
After discussion with Ryan, closing out as the jira associated with this was fixed another way.

**Pull request closed without merging**
