### PR TITLE
ENYO-4048: Allow for overriding of scroller options with falsy values.

### PR DESCRIPTION
**Pull request by aarontam**
Issue
-------
It is not currently possible to override scroller properties with falsy values (i.e. properties that are true by default, such as `useMouseWheel`).

Fix
----
Removed the `exists` option when mixing in `scrollerOptions` as there did not appear to be a current need for this (and there is no relevant history for the existence of this option here).

Enyo-DCO-1.1-Signed-off-by: Aaron Tam <aaron.tam@lge.com>

### CODE REVIEW

**Comment by lishammel** [comment]
@aarontam  - do we still need this PR merged? thanks.

**Comment by aarontam** [comment]
Hi @lishammel I believe we still need this but it had fallen off the radar. To be fair, it doesn't seem like the use case that exposed this issue is very common, but is still relevant.

**Comment by KunmyonChoi** [comment]
@aarontam Nice expression "fallen off the radar" :)

**Comment by lishammel** [comment]
Closing out as the jira attached to this has been closed

**Pull request closed without merging**
