### PR TITLE
DRD-10027 & ENYO-2003  Marquee is not starting for "Revoke all pairing authorizations" pop-up.

### PR DESCRIPTION
**Pull request by dmikey**
Issue.

So the font is slightly bigger, and that's the reason why we see an elipsis. The problem for the font being slightly bigger is caused by using -webkit-font-kerning: normal. This is ignored in blink. If you use font-kerning: normal it will work.

Fix.

Created a new normalizing plugin for Less.JS that will go through the rule sets, and create missing vendor prefixes or non-prefixed versions of the rules.

Enyo-DCO-1.1-Signed-off-by: Derek Anderson <derek.anderson@lge.com>

### CODE REVIEW

**Comment by aarontam** [comment]
We don't want to include all those node modules, right? :smile:

**Comment by dmikey** [comment]
I'm guessing not? I'm not sure how 2.6 works with this, I suspect they need to come along for the ride with 2.5 though?

**Comment by webOS101** [comment]
Is that a node module that should be installed with `npm install`?  Is it in the package.json?  Maybe that is the way to include it, but I don't know.

**Comment by aarontam** [comment]
Yeah I would imagine they would be dependencies (possibly of another dependency, here) that would be installed via `npm install`, and not need to be explicitly included.

**Comment by dmikey** [comment]
we don't use npm install for any of the 2.5 build tools however.

**Pull request closed without merging**
