### PR TITLE
fix for exceptions seen coming from transition scroller

### PR DESCRIPTION
**Pull request by MichaelRando**

### CODE REVIEW

**Comment by lishammel** [comment]
@MichaelRando  - would love some additional details on this.  Thanks!

**Comment by lishammel** [comment]
@MichaelRando  - let us know if you can provide additional details. Thanks!

**Comment by MichaelRando** [comment]
How can I help?

**Comment by lishammel** [comment]
Hi @MichaelRando  - per @dmikey  if you could give some more detail on when and where you see the scroller throwing exceptions that would be helpful for us to use to verify the fix. Thanks!

**Comment by MichaelRando** [comment]
It's a simple fix, I would imagine you could verify the fix by inspection, considering that you're splitting a value that has a possible equivalence to string 'none' and all my check did was not split it in that case. 
I think you could test it out if you called the old code redundantly, that 'none' string is right there.

**Comment by webOS101** [comment]
Michael, thanks for this pull request.  After some internal review we've decided not to take this pull request as we push out 2.7.  If you experience any of these issues with 2.7 we can look at new pull requests in the context of 2.7.

**Pull request closed without merging**
