### PR TITLE
ENYO-1638: accessibility - Button, Checkbox, Popup, Input, TextArea, …

### PR DESCRIPTION
**Pull request by jaewonjang**
…RichText support

Accessibility supporting for enyo UI - Button, Checkbox, Popup, Input,
TextArea, RichText

- Button: set button role and add 'aria-disabled' attribute matching
disabled property.
- Checkbox: set checkbox role and add 'aria-checked' attribute matching
checked property.
- Input: set textbox role and add 'aria-disabled' attribute matching
disabled property.
- Popup: set the 'accessibilityAlert' to read content of popup when it
is shown.
- RichText: set textbox role and 'aria-multiline' to true because
RichText supports multiline.
- TextArea: set textbox role and 'aria-multiline' to true.
At the moment RichText mixin and TextArea mixin are same, but I
separated them for maintenance.

https://jira2.lgsvl.com/browse/ENYO-1638
Enyo-DCO-1.1-Signed-off-by: Jaewon Jang <jaewon98.jang@lgepartner.com>

### CODE REVIEW

**Comment by jaewonjang** [comment]
This PR has dependency on https://github.com/enyojs/enyo/pull/1148

**Comment by seunghoh** [comment]
Code looks good to me but each XXXXAccessibilitySupport.js should be in the XXXX folder?

**Comment by jaewonjang** [comment]
moved XXXX.js and XXXXAccessibilitySupport.js into sample folder.

**Comment by jaewonjang** [comment]
rebased 2.6.0-dev

**Comment by ryanjduffy** [comment]
Something went awry in the process of your merge/rebase so I'm going to close this and supercede with #1182.

**Pull request closed without merging**
